### ISSUE TITLE
[Suggestion] Visual effects with EV

### ISSUE THREAD

**Issue by ghost** [vemerion/Wizard-Staff#2]
Hi, 
The visual effect for the pumpkin power will be nice - [Enhanced Visuals](https://github.com/CreativeMD/EnhancedVisuals) compatibility - screen will be red(like vignette but red). I know Java, so I'll help you :)
[Suggestion for visuals in EV's repo](https://github.com/CreativeMD/EnhancedVisuals/issues/66)

**Comment by vemerion** [comment]
Hello?

It seems like the user that suggested this has deleted their account. In either case, while I like the Enhanced Visuals mod, I feel like there are other things I would rather focus on adding (more spells mainly) than Enhanced Visuals compatibility. For this reason I will close this issue.
