### ISSUE TITLE
Switching gamemodes can cause item in wizard staff to disappear. 

### ISSUE THREAD

**Issue by Cinderheart** [vemerion/Wizard-Staff#3]
Switch between gamemodes (creative, survival, and spectator) with a wizard staff in inventory (not hotbar) and eventually the item in the staff will vanish.

**Comment by vemerion** [comment]
Hello Cinderheart!

Did this occur on a dedicated server? Because if so, this is unfortunately a vanilla/forge bug, and I can't do anything about it. See [this](https://github.com/MinecraftForge/MinecraftForge/issues/7359) issue for more information about it.

**Comment by Cinderheart** [comment]
Yes sadly. Well, thanks for letting me know, now I know how to avoid triggering it.

**Comment by vemerion** [comment]
Alright then, I'll go ahead and close the issue, since the bug is out of my hands.
