### ISSUE TITLE
Connection with ice and fire and wizzard staff 1.16.5 [forge 36.0.45]

### ISSUE THREAD

**Issue by FurryApocalypse** [vemerion/Wizard-Staff#4]
It's probably global bug and its about connection with other mod.
In wizzard-staff mod you can cast a spell that turns mobs into spawn eggs.
Problem here is that dragon skeletons are counted as mobs aswell so you can kill dragon, take some of stuff and reborn it again by changin last tick of skeleton into spawn egg.
I post this ticket here couse im not sure should i rather noticed it to wizzard staff creator or ice and fire.
(this issue us posted for both creator right now)

**Comment by vemerion** [comment]
Thank you so much for bringing this to my attention! I will include a blacklist in the json file for the egg spell in the next update (scheduled for tomorrow), so that players can easily configure the spell to exclude certain entities.

**Comment by vemerion** [comment]
The Wizard Staff 1.5 update is now out, with a blacklist for the egg magic to solve this problem! You can look at the specific commit [here](https://github.com/vemerion/Wizard-Staff/commit/0e152e2bc37e3906d37539eb02a9a9f210609623) for the details.

I will close this issue with this comment.
